// <auto-generated />
using System;
using Ground_Storage_WebAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ground_Storage_WebAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20201208194302_some columns added")]
    partial class somecolumnsadded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Ground_Storage_WebAPI.Models.Key", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("TEXT");

                    b.HasKey("Name", "RecordId");

                    b.HasIndex("Name", "RecordId");

                    b.ToTable("Keys");
                });

            modelBuilder.Entity("Ground_Storage_WebAPI.Models.Record", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Entity")
                        .HasColumnType("TEXT");

                    b.Property<string>("Group")
                        .HasColumnType("TEXT");

                    b.Property<string>("Keys")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Rev")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Entity", "Group");

                    b.ToTable("Records");
                });
#pragma warning restore 612, 618
        }
    }
}
